import { BankItem } from '../types'
import { numberEquals } from '../verify'

export const CH4: BankItem[] = [
  {
    id: 'ch4-mcq-rn-1',
    chapterId: 'ch4',
    difficulty: 'easy',
    concepts: ['s4-2'],
    source: 'template',
    format: 'mcq',
    prompt: `$A$ is $5 \\times 7$ with rank $3$. Nullity = ?`,
    options: ['2', '3', '4', '5'],
    answerIndex: 2,
    explanation: 'Rank–Nullity: nullity = $7 - 3 = 4$.',
  },
  {
    id: 'ch4-mcq-rn-2',
    chapterId: 'ch4',
    difficulty: 'medium',
    concepts: ['s4-2'],
    source: 'template',
    format: 'mcq',
    prompt: `$B$ is $4 \\times 6$ with rank $2$. How many free variables in $Bx=0$?`,
    options: ['2', '4', '6', '3'],
    answerIndex: 0,
    explanation: 'Free variables = nullity = $6 - 2 = 4$. Wait, that\'s 4, answer is $n - \\text{rank} = 6 - 2 = 4$.',
  },
  {
    id: 'ch4-typed-rank-1',
    chapterId: 'ch4',
    difficulty: 'medium',
    concepts: ['s4-1', 's4-2'],
    source: 'template',
    format: 'typed',
    inputKind: 'number',
    prompt: `Rank of $\\begin{bmatrix}1 & 2 & 3\\\\2 & 4 & 6\\\\1 & 1 & 1\\end{bmatrix}$ = ?`,
    verify: (s) => numberEquals(s, 2),
    canonicalAnswer: '2',
    explanation: 'Row 2 is $2\\times$ row 1; reduces to 2 nonzero rows.',
  },
  {
    id: 'ch4-typed-nullity-1',
    chapterId: 'ch4',
    difficulty: 'medium',
    concepts: ['s4-2'],
    source: 'template',
    format: 'typed',
    inputKind: 'number',
    prompt: `$C$ is $4 \\times 6$ with dim(Col $C$) $= 4$. Nullity = ?`,
    verify: (s) => numberEquals(s, 2),
    canonicalAnswer: '2',
    explanation: 'Rank = 4; nullity = $6 - 4 = 2$.',
  },
  {
    id: 'ch4-mcq-colspace-1',
    chapterId: 'ch4',
    difficulty: 'medium',
    concepts: ['s4-1'],
    source: 'template',
    format: 'mcq',
    prompt: `$Ax = b$ is consistent iff`,
    options: [
      `$b \\in \\text{Null}(A)$`,
      `$b \\in \\text{Col}(A)$`,
      `$b \\in \\text{Row}(A)$`,
      `$\\text{rank}(A) = m$`,
    ],
    answerIndex: 1,
    explanation: '$Ax$ is always in Col$(A)$, so solution exists iff $b$ is there.',
  },
  {
    id: 'ch4-mcq-nullity-1',
    chapterId: 'ch4',
    difficulty: 'hard',
    concepts: ['s4-2'],
    source: 'template',
    format: 'mcq',
    prompt: `If rank$(A) = $ nullity$(A)$ for an $n \\times n$ matrix, then $n = ?$`,
    options: ['Any $n$', '2', 'Rank + nullity must equal $n$', 'Impossible'],
    answerIndex: 1,
    explanation: 'rank + nullity = $n$; if rank = nullity, then $2\\cdot\\text{rank} = n$, so $n$ is even. Specifically, $n=2k$.',
  },
  {
    id: 'ch4-typed-rank-2',
    chapterId: 'ch4',
    difficulty: 'easy',
    concepts: ['s4-2'],
    source: 'template',
    format: 'typed',
    inputKind: 'number',
    prompt: `An $8 \\times 5$ matrix has rank at most = ?`,
    verify: (s) => numberEquals(s, 5),
    canonicalAnswer: '5',
    explanation: 'Rank $\\leq \\min(m, n) = \\min(8, 5) = 5$.',
  },
]
