import { BankItem } from '../types'
import { numberEquals, vectorEquals } from '../verify'

export const CH5: BankItem[] = [
  {
    id: 'ch5-mcq-ortho-1',
    chapterId: 'ch5',
    difficulty: 'easy',
    concepts: ['s5-1'],
    source: 'template',
    format: 'mcq',
    prompt: `Which pair is orthogonal in $\\mathbb{R}^3$?`,
    options: [
      `$(1, 2, 3)$ and $(1, 1, 1)$`,
      `$(1, -2, 1)$ and $(2, 1, 0)$`,
      `$(1, 0, 1)$ and $(1, 0, 1)$`,
      `$(1, 1, 0)$ and $(1, 1, 0)$`,
    ],
    answerIndex: 1,
    explanation: '$(1,-2,1)\\cdot(2,1,0) = 2 - 2 + 0 = 0$.',
  },
  {
    id: 'ch5-mcq-ortho-2',
    chapterId: 'ch5',
    difficulty: 'medium',
    concepts: ['s5-1'],
    source: 'template',
    format: 'mcq',
    prompt: `If $u \\perp v$ (orthogonal), then $u \\cdot v = ?$`,
    options: ['0', '1', '$\\|u\\| \\|v\\|$', '−1'],
    answerIndex: 0,
    explanation: 'Orthogonal vectors have dot product zero.',
  },
  {
    id: 'ch5-typed-proj-1',
    chapterId: 'ch5',
    difficulty: 'medium',
    concepts: ['s5-3'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `$u = (3, 4)$, $v = (1, 0)$. Find $\\text{proj}_v(u)$. Enter as $(a, b)$.`,
    verify: (s) => vectorEquals(s, [3, 0]),
    canonicalAnswer: '(3, 0)',
    explanation: '$\\text{proj}_v(u) = (u\\cdot v / v\\cdot v) v = 3(1,0) = (3,0)$.',
  },
  {
    id: 'ch5-typed-proj-2',
    chapterId: 'ch5',
    difficulty: 'hard',
    concepts: ['s5-3'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `$u = (1, 2, 2)$, $v = (1, 0, 0)$. Compute $\\text{proj}_v(u)$ as $(a, b, c)$.`,
    verify: (s) => vectorEquals(s, [1, 0, 0]),
    canonicalAnswer: '(1, 0, 0)',
  },
  {
    id: 'ch5-mcq-qr-1',
    chapterId: 'ch5',
    difficulty: 'medium',
    concepts: ['s5-4'],
    source: 'template',
    format: 'mcq',
    prompt: `QR factorization requires`,
    options: [
      '$A$ square',
      'Columns linearly independent (and $m \\geq n$)',
      'Rows linearly independent',
      '$A$ invertible',
    ],
    answerIndex: 1,
    explanation: 'Gram–Schmidt needs independent columns and $m \\geq n$ for orthonormal vectors.',
  },
  {
    id: 'ch5-mcq-gram-schmidt-1',
    chapterId: 'ch5',
    difficulty: 'hard',
    concepts: ['s5-2'],
    source: 'template',
    format: 'mcq',
    prompt: `Gram–Schmidt orthogonalizes via`,
    options: [
      'Subtracting projections onto previous vectors',
      'Scaling each vector to unit norm',
      'Taking cross products',
      'Solving a linear system',
    ],
    answerIndex: 0,
    explanation: 'Gram–Schmidt: $v_k := u_k - \\sum_{i<k} \\text{proj}_{v_i}(u_k)$.',
  },
  {
    id: 'ch5-typed-dist-1',
    chapterId: 'ch5',
    difficulty: 'easy',
    concepts: ['s5-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'number',
    prompt: `$\\|u - v\\|^2$ where $u = (2, 3, 1)$, $v = (1, 1, 0)$ = ?`,
    verify: (s) => numberEquals(s, 6),
    canonicalAnswer: '6',
    explanation: '$u - v = (1, 2, 1)$; $\\|u-v\\|^2 = 1 + 4 + 1 = 6$.',
  },
  {
    id: 'ch5-mcq-orthonormal-1',
    chapterId: 'ch5',
    difficulty: 'medium',
    concepts: ['s5-2'],
    source: 'template',
    format: 'mcq',
    prompt: `An orthonormal set has`,
    options: ['Pairwise orthogonal vectors', 'Unit-norm vectors', 'Both orthogonal and unit-norm', 'Linear independence'],
    answerIndex: 2,
    explanation: 'Orthonormal: pairwise orthogonal AND each has norm 1.',
  },
]
