import { BankItem } from '../types'
import { numberEquals, numberSetEquals, vectorEqualsUpToScale } from '../verify'

export const CH6: BankItem[] = [
  {
    id: 'ch6-typed-eig-diag-1',
    chapterId: 'ch6',
    difficulty: 'easy',
    concepts: ['s6-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `Eigenvalues of $\\begin{bmatrix}2 & 0 & 0\\\\0 & -1 & 0\\\\0 & 0 & 5\\end{bmatrix}$ (any order)?`,
    verify: (s) => numberSetEquals(s, [2, -1, 5]),
    canonicalAnswer: '2, -1, 5',
    explanation: 'Diagonal entries are the eigenvalues.',
  },
  {
    id: 'ch6-typed-eig-tri-1',
    chapterId: 'ch6',
    difficulty: 'easy',
    concepts: ['s6-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `Eigenvalues of $\\begin{bmatrix}3 & 1 & 2\\\\0 & -1 & 0\\\\0 & 0 & 2\\end{bmatrix}$ (any order)?`,
    verify: (s) => numberSetEquals(s, [3, -1, 2]),
    canonicalAnswer: '3, -1, 2',
    explanation: 'Triangular: eigenvalues = diagonal entries.',
  },
  {
    id: 'ch6-typed-eig-2x2-1',
    chapterId: 'ch6',
    difficulty: 'medium',
    concepts: ['s6-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `Eigenvalues of $\\begin{bmatrix}4 & 1\\\\2 & 3\\end{bmatrix}$ (any order)?`,
    verify: (s) => numberSetEquals(s, [2, 5]),
    canonicalAnswer: '2, 5',
    explanation: '$\\det(A-\\lambda I) = (4-\\lambda)(3-\\lambda) - 2 = \\lambda^2 - 7\\lambda + 10$.',
  },
  {
    id: 'ch6-typed-eig-2x2-2',
    chapterId: 'ch6',
    difficulty: 'hard',
    concepts: ['s6-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `Eigenvalues of $\\begin{bmatrix}5 & 2\\\\1 & 4\\end{bmatrix}$ (any order)?`,
    verify: (s) => numberSetEquals(s, [3, 6]),
    canonicalAnswer: '3, 6',
    explanation: '$\\det(A-\\lambda I) = (5-\\lambda)(4-\\lambda) - 2 = \\lambda^2 - 9\\lambda + 18 = (\\lambda-3)(\\lambda-6)$.',
  },
  {
    id: 'ch6-typed-eigvec-1',
    chapterId: 'ch6',
    difficulty: 'hard',
    concepts: ['s6-1', 's6-2'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `Eigenvector of $\\begin{bmatrix}2 & 1\\\\0 & 3\\end{bmatrix}$ for $\\lambda = 3$ (any scale)?`,
    verify: (s) => vectorEqualsUpToScale(s, [1, 1]),
    canonicalAnswer: '(1, 1)',
    explanation: '$(A - 3I)x = 0$: $\\begin{bmatrix}-1 & 1\\\\0 & 0\\end{bmatrix}x = 0 \\Rightarrow x_1 = x_2$.',
  },
  {
    id: 'ch6-mcq-spectral-1',
    chapterId: 'ch6',
    difficulty: 'medium',
    concepts: ['s6-3'],
    source: 'template',
    format: 'mcq',
    prompt: `Orthogonal diagonalizability iff`,
    options: [
      '$A$ invertible',
      '$A$ symmetric',
      '$A$ has $n$ distinct eigenvalues',
      '$A$ is upper triangular',
    ],
    answerIndex: 1,
    explanation: 'Spectral theorem: orthogonally diagonalizable $\\Leftrightarrow$ $A = A^T$.',
  },
  {
    id: 'ch6-mcq-trace-1',
    chapterId: 'ch6',
    difficulty: 'medium',
    concepts: ['s6-1'],
    source: 'template',
    format: 'mcq',
    prompt: `If eigenvalues of $A$ are $1, 2, 3$, then $\\det(A) = ?$`,
    options: ['6', '5', '0', '36'],
    answerIndex: 0,
    explanation: '$\\det(A)$ = product of eigenvalues = $1 \\cdot 2 \\cdot 3 = 6$.',
  },
  {
    id: 'ch6-typed-det-from-eig-1',
    chapterId: 'ch6',
    difficulty: 'medium',
    concepts: ['s6-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'number',
    prompt: `Eigenvalues of $3\\times 3$ matrix are $2, -1, 4$. Then $\\det(A) = ?$`,
    verify: (s) => numberEquals(s, -8),
    canonicalAnswer: '-8',
    explanation: 'Product: $2 \\cdot (-1) \\cdot 4 = -8$.',
  },
  {
    id: 'ch6-mcq-diag-1',
    chapterId: 'ch6',
    difficulty: 'hard',
    concepts: ['s6-2'],
    source: 'template',
    format: 'mcq',
    prompt: `$A$ is diagonalizable iff`,
    options: [
      'It has $n$ eigenvalues',
      'It has $n$ linearly independent eigenvectors',
      'It is symmetric',
      'It is invertible',
    ],
    answerIndex: 1,
    explanation: 'Diagonalizable: $P^{-1}AP = D$ iff columns of $P$ (eigenvectors) are linearly independent.',
  },
]
