import { BankItem } from '../types'
import { vectorEquals, matrixEquals } from '../verify'

export const CH7: BankItem[] = [
  {
    id: 'ch7-mcq-lin-1',
    chapterId: 'ch7',
    difficulty: 'easy',
    concepts: ['s7-1'],
    source: 'template',
    format: 'mcq',
    prompt: `Which is linear?`,
    options: [
      `$T(x, y) = (x + 1, y)$`,
      `$T(x, y) = (x^2, y)$`,
      `$T(x, y) = (2x - y, x + 3y)$`,
      `$T(x, y) = (|x|, y)$`,
    ],
    answerIndex: 2,
    explanation: 'Only option (c) is $T(v) = Av$ (a matrix map); others violate $T(0) = 0$ or linearity.',
  },
  {
    id: 'ch7-mcq-lin-2',
    chapterId: 'ch7',
    difficulty: 'medium',
    concepts: ['s7-1'],
    source: 'template',
    format: 'mcq',
    prompt: `$T$ is linear iff it preserves`,
    options: [
      'Addition only',
      'Scalar multiplication only',
      'Both addition and scalar multiplication',
      'Orthogonality',
    ],
    answerIndex: 2,
    explanation: 'Linearity: $T(au + bv) = aT(u) + bT(v)$ for all scalars and vectors.',
  },
  {
    id: 'ch7-typed-rot-1',
    chapterId: 'ch7',
    difficulty: 'medium',
    concepts: ['s7-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'matrix',
    prompt: `Standard matrix for $90°$ counterclockwise rotation in $\\mathbb{R}^2$ (enter as \`a,b;c,d\`)?`,
    verify: (s) => matrixEquals(s, [[0, -1], [1, 0]]),
    canonicalAnswer: '0,-1;1,0',
    explanation: '$T(e_1) = (0, 1)$, $T(e_2) = (-1, 0)$.',
  },
  {
    id: 'ch7-typed-rot-2',
    chapterId: 'ch7',
    difficulty: 'hard',
    concepts: ['s7-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'matrix',
    prompt: `Matrix for reflection across the $x$-axis (format \`a,b;c,d\`)?`,
    verify: (s) => matrixEquals(s, [[1, 0], [0, -1]]),
    canonicalAnswer: '1,0;0,-1',
    explanation: '$(x, y) \\mapsto (x, -y)$.',
  },
  {
    id: 'ch7-typed-apply-1',
    chapterId: 'ch7',
    difficulty: 'easy',
    concepts: ['s7-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `$A = \\begin{bmatrix}1 & 2\\\\3 & 4\\end{bmatrix}$. $T(1, -1) = ?$ (as $(a, b)$)`,
    verify: (s) => vectorEquals(s, [-1, -1]),
    canonicalAnswer: '(-1, -1)',
  },
  {
    id: 'ch7-typed-apply-2',
    chapterId: 'ch7',
    difficulty: 'medium',
    concepts: ['s7-1'],
    source: 'template',
    format: 'typed',
    inputKind: 'vector',
    prompt: `$A = \\begin{bmatrix}2 & -1\\\\1 & 3\\end{bmatrix}$. $T(2, 1) = ?$ as $(a, b)$.`,
    verify: (s) => vectorEquals(s, [3, 5]),
    canonicalAnswer: '(3, 5)',
  },
  {
    id: 'ch7-mcq-inj-1',
    chapterId: 'ch7',
    difficulty: 'medium',
    concepts: ['s7-2'],
    source: 'template',
    format: 'mcq',
    prompt: `$T: \\mathbb{R}^n \\to \\mathbb{R}^m$ is injective iff`,
    options: [
      `$\\ker(T) = \\{0\\}$`,
      `\\text{rank}(T) = m$`,
      `$T$ is surjective`,
      `$n = m$`,
    ],
    answerIndex: 0,
    explanation: 'Injectivity $\\Leftrightarrow$ trivial kernel.',
  },
  {
    id: 'ch7-mcq-surj-1',
    chapterId: 'ch7',
    difficulty: 'hard',
    concepts: ['s7-2'],
    source: 'template',
    format: 'mcq',
    prompt: `$T: \\mathbb{R}^n \\to \\mathbb{R}^m$ is surjective iff`,
    options: [
      `$\\ker(T) = \\{0\\}$`,
      `R(T) = \\mathbb{R}^m$`,
      `\\text{rank}(T) = n$`,
      `Columns of $A$ are independent`,
    ],
    answerIndex: 1,
    explanation: 'Surjectivity $\\Leftrightarrow$ range is the codomain.',
  },
  {
    id: 'ch7-mcq-bij-1',
    chapterId: 'ch7',
    difficulty: 'hard',
    concepts: ['s7-2'],
    source: 'template',
    format: 'mcq',
    prompt: `$T: \\mathbb{R}^n \\to \\mathbb{R}^n$ is bijective iff`,
    options: [
      '$A$ has rank $< n$',
      '$A$ is invertible (rank $= n$)',
      '$\\ker(T) \\neq \\{0\\}$',
      '$A$ is singular',
    ],
    answerIndex: 1,
    explanation: 'Bijective: both injective and surjective, so rank $= n$ and $A$ invertible.',
  },
]
